### ISSUE TITLE
The Jupiter notebook tutorial returns 404 error

### ISSUE THREAD

**Issue by bravemaster3** [stanfordmlgroup/methane-gapfill-ml#12]
Thank you for these codes. Unfortunately, the jupyter notebook link is not functional now.
Based on your recommendations in your paper, I actually implemented random forest for gapfilling methane fluxes in R (10-fold cross validation in my case). I am not good with python codes, and I was hoping to understand how you assessed the uncertainty.
In addition, I can't figure out how the yearly sine-cosine are calculated. For now I use some linear continuous variable for each season (min 0, max 1 picking in the middle of each season) as predictors in the random forest. While my model works perfectly fine, I wanted to test the yearly sine and cosines too.

I wrote a lote in here, but I hope you get to give me some ideas...
Thanks,
Koffi

**Comment by bravemaster3** [comment]
> Thank you for these codes. Unfortunately, the jupyter notebook link is not functional now. Based on your recommendations in your paper, I actually implemented random forest for gapfilling methane fluxes in R (10-fold cross validation in my case). I am not good with python codes, and I was hoping to understand how you assessed the uncertainty. In addition, I can't figure out how the yearly sine-cosine are calculated. For now I use some linear continuous variable for each season (min 0, max 1 picking in the middle of each season) as predictors in the random forest. While my model works perfectly fine, I wanted to test the yearly sine and cosines too.
> 
> I wrote a lote in here, but I hope you get to give me some ideas... Thanks, Koffi

For the temporal predictors, I found them in your codes, and I will translate them into R and use it. That should be fine now.
Thanks,
Koffi

**Comment by ylzhouchris** [comment]
Thanks! We've updated the link to the jupyter notebook: https://github.com/stanfordmlgroup/methane-gapfill-ml/blob/master/fluxgapfill_tutorial.ipynb
