### ISSUE TITLE
'ANN' object has no attribute 'scaler'

### ISSUE THREAD

**Issue by ylzhouchris** [stanfordmlgroup/methane-gapfill-ml#9]
when training with models="ann", got the titled error message. The error traces back to Line 57 of models/base.py. @jirvin16

**Comment by jirvin16** [comment]
I think the ANN should have a scaler (inputs to the ANN should be standardized), so you'll want to add a line similar to this one:
https://github.com/stanfordmlgroup/methane-gapfill-ml/blob/f6933753a04b93e4848a0e89cb000d7b0be76c97/fluxgapfill/models/models.py#L22
on line 52 instead.
